// utils/ptlExport.ts
import { PTL_BRAND, getBrandLogoUrl } from "@/components/Branding";

export interface Holding {
  outcome: string;
  short_order: string;
  quoted_lines: string[];
}

export interface JudgmentSummary {
  case_title: string;
  court: string;
  decision_date: string | null;
  bench: string[];
  procedural_history: string;
  key_facts: string;
  issues: string[];
  holding: Holding;
  citations: string[];
  takeaways: string[];
}

/* TXT + COPY (branded) */
export function summaryToBrandedText(s: JudgmentSummary) {
  return `
${PTL_BRAND.name}
${PTL_BRAND.site}
================================

CASE SUMMARY
============

Case Title: ${s.case_title}
Court: ${s.court}
Decision Date: ${s.decision_date || "Not mentioned"}
Bench: ${s.bench.join(", ") || "Not mentioned"}

PROCEDURAL HISTORY
${s.procedural_history}

KEY FACTS
${s.key_facts}

ISSUES
${s.issues.map((i, idx) => `${idx + 1}. ${i}`).join("\n")}

HOLDING
Outcome: ${s.holding.outcome}
Order: ${s.holding.short_order}

CITATIONS
${s.citations.length > 0 ? s.citations.join("\n") : "None cited"}

KEY TAKEAWAYS
${s.takeaways.map((t, idx) => `${idx + 1}. ${t}`).join("\n")}

--------------------------------
${PTL_BRAND.signatureLine}
`.trim();
}

/* HTML used for DOC + Print/PDF */
export function summaryToBrandedHtml(s: JudgmentSummary) {
  const logoUrl = getBrandLogoUrl(false);
  const today = new Date().toLocaleDateString();

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>${s.case_title}</title>
<style>
  body { font-family: Times New Roman, serif; padding: 24px; line-height: 1.6; }
  .header, .footer {
    background: ${PTL_BRAND.orange};
    color: #fff;
    padding: 10px 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-radius: 8px;
  }
  .header { margin-bottom: 16px; }
  .footer { margin-top: 20px; font-size: 12px; }
  .brand { display: flex; gap: 10px; align-items: center; }
  .logo { width: 36px; height: 36px; object-fit: contain; }
  h1 { border-bottom: 2px solid ${PTL_BRAND.orange}; }
</style>
</head>
<body>

<div class="header">
  <div class="brand">
    <img src="${logoUrl}" class="logo" />
    <strong>${PTL_BRAND.name}</strong>
  </div>
  <div>${PTL_BRAND.site.replace("https://", "")}</div>
</div>

<h1>${s.case_title}</h1>
<p><strong>Court:</strong> ${s.court}</p>
<p><strong>Date:</strong> ${s.decision_date || "Not mentioned"}</p>

<h2>Summary</h2>
<p>${s.key_facts}</p>

<div class="footer">
  <div>Generated by ${PTL_BRAND.name}</div>
  <div>${today}</div>
</div>

</body>
</html>
`.trim();
}
